# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160220_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated_at', '-pk')},
        ),
    ]
